config/routes.rb
bundle exec rake routesRails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 resources :contacts
  get '/live' => 'pages#live'
  get '/employment' => 'pages#employment'
  get '/professional' => 'pages#professional'
  get '/applications' => 'pages#applications'
  get '/about' => 'pages#about'
  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
####app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end
	
	def create
	end
end

app/controllers/contract_controller.rb
####app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
	 end
	def create
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/new.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="well">
      <%= form_for @contact do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :comments %>
          <%= f.text_area :comments, class: 'form-control' %>
        </div>
        <%= f.submit 'Submit', class: 'btn btn-default' %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelpDesk</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
	  <div class='container'>
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <%= link_to root_path, class: 'navbar-brand' do %>
	      	<i class="fa fa-headphones" aria-hidden="true"></i>
	      	HelpDesk
	      <% end %>
	    </div>

<!-- 	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	 
	       </ul>
	    </div>
	    
		<form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->

	    <div class="collapse navbar-collapse" id="main-nav-collapse">
	      <ul class="nav navbar-nav navbar-right">
       		<li><%= link_to "Applications", applications_path%></li>
	        <li><%= link_to "About", about_path%></li>
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div>
	</nav>	

	<div class ="container">
		<%= yield %>
	</div>

  </body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>About Us</title>
</head>
<body>
	<div class = "jumbotron text-left">
		<h3>About Us</h3>
		<p>For immediate assistance please contact our support staff via phone or sms: (+61) 0406 886 677</p>
	</div>
</body>
</html>

app/views/pages/applications.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Applications</title> 
</head>
<body>
	<div class="jumbotron text-center btn-group btn-group-justified" role="group" aria-label="...">
	  <div class="btn-group" role="group">
	    <button type="button" class="btn btn-default">
			<li><%= link_to "Employment Reference", employment_path%></li>
	    </button>
	  </div>
	  <div class="btn-group" role="group">
	    <button type="button" class="btn btn-default">
	    	<li><%= link_to "Professional Reference", professional_path%></li>
	    </button>
	  </div>
	  <div class="btn-group" role="group">
	    <button type="button" class="btn btn-default">
			<li><%= link_to "Live Reference", live_path%></li>
	    </button>
	  </div>
	</div>

</body>
</html>

app/views/pages/contact.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Contact Us</title>
</head>
<body>
	<div class = "jumbotron text-left">
		<h3>Contact Us</h3>
		<p>For immediate assistance please contact our support staff via phone or sms: (+61) 0406 886 677</p>
	</div>
</body>
</html>

app/views/pages/employment.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Employment Reference</title>
</head>
<body>
	<div class = "jumbotron text-center">
		<h1>Employment Reference</h1>
	</div>
</body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Help Desk</title>
</head>
<body>
	<div class = "jumbotron text-center">
		<h1>Welcome to Tenant Options</h1>
		<p>Tenant Options is an application efficiency program that streamlines the rental application process through smart referencing for Property Managers.</p>
	</div>


</body>
</html>

app/views/pages/live.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Living Reference</title>
</head>
<body>
	<div class = "jumbotron text-center">
		<h1>Live Reference</h1>
	</div>
</body>
</html>

app/views/pages/professional.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Professional Reference</title>
</head>
<body>
	<div class = "jumbotron text-center">
		<h1>Professional Reference</h1>
	</div>
</body>
</html>